### ISSUE TITLE
Project_Avengers_Completed_Carson_Weifeng_Sheng

### ISSUE THREAD

**Issue by cahoffman** [cahoffman/statWORK679#4]
@cecileane
https://github.com/UWMadison-computingtools/project1-avengers/commit/1d7bac1bbaac7a11e545d45edf41a3a8b0bdaee0

Hello Cecil,
We have completed our project by following all the detailed instructions on the course website. If you have any questions let us know. Thanks.
-Carson, Sheng, Weifeng

**Comment by cecileane** [comment]
Hi Carson, @ZhuWeifeng94 and @anyezijue49,
Could you please open a new issue on your project repository [here](https://github.com/UWMadison-computingtools/project1-avengers/issues) with the same message, then close this issue? After you do so, I will comment on that other issue (for the group project repo) and tag others so they get a message to provide feedback. Thanks!

**Comment by cahoffman** [comment]
Thanks sorry about that I think I fixed it.
